using UnityEngine;

public class GameManager : MonoBehaviour


{

    public int bestScore;
    public int currentScore;

    public int currentLevel = 0;

    public static GameManager singleton;


        void Awake()
        
    {
  if (singleton ==null)
        {
           singleton = this; 
        }

        else if (singleton!= this)
        {
            
            Destroy(gameObject);
        }



    }


    public void NextLeve()
    {
        
    }

    public void RestartLevel()
    {
        
    }


public void AddScore( int scoreToAdd)
    {
        
        currentScore += scoreToAdd;
        if (currentScore>bestScore)
        {
            
            bestScore = currentScore;
        }
    }
  
    void Update()



    {
        
    }
}

